# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master", "main", $default-branch ]
  pull_request:
    branches: [ "master", "main", $default-branch ]

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
      with:
        egress-policy: audit

    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

    - name: Set up Go
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        go-version: '1.22'

    - name: Go Vet
      run: go vet ./...

    - uses: dominikh/staticcheck-action@v1.3.1
      with:
        version: "latest"
        install-go: false

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
